apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep01susi
  labels:
    app: httpd
  namespace: dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: nodejs-container
          image: ujjwalbudha000/myrepo:v9
  selector:
    matchLabels:
      app: httpd
